figma.showUI(__html__, { width: 420, height: 720, themeColors: true });

const PLUGIN_OWNER_KEY = "dsb-owner";
const PLUGIN_OWNER_VALUE = "design-system-builder";
const PLUGIN_DESCRIPTION_MARKER = "[Generated by Design System Builder]";
let currentWriteTracker = null;

// BEGIN GENERATED DESIGN SYSTEM RULES
// Source: ../design-system-builder-web/rules/config.js
const RULES = {
  "white": "#FFFFFF",
  "darkAnchor": "#111827",
  "forbiddenBlack": "#000000",
  "brand": [
    {
      "name": "Brand/primary-light-2",
      "mixWith": "white",
      "amount": 0.72
    },
    {
      "name": "Brand/primary-light-1",
      "mixWith": "white",
      "amount": 0.42
    },
    {
      "name": "Brand/primary",
      "source": true
    },
    {
      "name": "Brand/primary-dark-1",
      "mixWith": "darkAnchor",
      "amount": 0.28
    },
    {
      "name": "Brand/primary-dark-2",
      "mixWith": "darkAnchor",
      "amount": 0.48
    }
  ],
  "semantic": {
    "toneFollow": {
      "lightness": 0.24,
      "saturation": 0.18
    },
    "tintOpacity": 0.1,
    "baseColors": [
      {
        "name": "Semantic/success",
        "value": "#24A06B",
        "groups": [
          "full",
          "red-green"
        ],
        "toneGuard": {
          "minLightness": 0.38,
          "maxLightness": 0.58,
          "minSaturation": 0.42,
          "maxSaturation": 0.72
        }
      },
      {
        "name": "Semantic/warning",
        "value": "#D99624",
        "groups": [
          "full"
        ],
        "toneGuard": {
          "minLightness": 0.44,
          "maxLightness": 0.62,
          "minSaturation": 0.56,
          "maxSaturation": 0.82
        }
      },
      {
        "name": "Semantic/error",
        "value": "#D94E61",
        "groups": [
          "full",
          "red-green"
        ],
        "toneGuard": {
          "minLightness": 0.42,
          "maxLightness": 0.62,
          "minSaturation": 0.5,
          "maxSaturation": 0.78
        }
      },
      {
        "name": "Semantic/info",
        "value": "#3484D9",
        "groups": [
          "full"
        ],
        "toneGuard": {
          "minLightness": 0.4,
          "maxLightness": 0.62,
          "minSaturation": 0.48,
          "maxSaturation": 0.78
        }
      }
    ]
  },
  "neutral": {
    "solidLevels": [
      900,
      800,
      700,
      600,
      500,
      400,
      300,
      200,
      100,
      50,
      "00"
    ],
    "solidMix": [
      0,
      0.1,
      0.21,
      0.34,
      0.48,
      0.62,
      0.75,
      0.84,
      0.91,
      0.965,
      1
    ],
    "standardOverlay": [
      100,
      80,
      60,
      40,
      20,
      10,
      5
    ],
    "lightweightBlackOverlay": [
      100,
      80,
      60,
      40,
      20,
      15,
      10,
      5
    ],
    "lightweightWhiteOverlay": [
      100,
      90,
      80,
      60,
      40,
      20,
      10,
      5
    ]
  },
  "auxiliary": [
    {
      "name": "Auxiliary/base",
      "source": true
    },
    {
      "name": "Auxiliary/02",
      "mixWith": "white",
      "amount": 0.5
    },
    {
      "name": "Auxiliary/03",
      "mixWith": "white",
      "amount": 0.9
    }
  ],
  "lightDark": {
    "backgroundToneMapping": {
      "model": "OKLCH",
      "note": "Light / Dark 背景填一个即可，另一个按 OKLCH Tone Mapping 自动推算；两个都填则使用手动值。",
      "darkFromLight": {
        "minLightness": 0.19,
        "maxLightness": 0.23,
        "baseLightness": 0.195,
        "sourceLightnessInfluence": 0.14,
        "chromaMultiplier": 0.45,
        "maxChroma": 0.035
      },
      "lightFromDark": {
        "minLightness": 0.955,
        "maxLightness": 0.985,
        "baseLightness": 0.985,
        "sourceLightnessInfluence": 0.12,
        "chromaMultiplier": 0.35,
        "maxChroma": 0.025
      }
    }
  },
  "typography": {
    "compact": [
      [
        "Headline/H1",
        "Semi Bold",
        30,
        38
      ],
      [
        "Headline/H2",
        "Semi Bold",
        24,
        32
      ],
      [
        "Headline/H3",
        "Semi Bold",
        20,
        28
      ],
      [
        "Title",
        "Semi Bold",
        18,
        26
      ],
      [
        "Subtitle",
        "Semi Bold",
        16,
        24
      ],
      [
        "Body",
        "Regular",
        14,
        22
      ],
      [
        "Caption",
        "Regular",
        12,
        18
      ]
    ],
    "full": [
      [
        "Headline/H1",
        "Semi Bold",
        36,
        44
      ],
      [
        "Headline/H2",
        "Semi Bold",
        32,
        40
      ],
      [
        "Headline/H3",
        "Semi Bold",
        28,
        36
      ],
      [
        "Headline/H4",
        "Semi Bold",
        26,
        34
      ],
      [
        "Headline/H5",
        "Semi Bold",
        24,
        32
      ],
      [
        "Subtitle/S1",
        "Semi Bold",
        16,
        24
      ],
      [
        "Subtitle/S2",
        "Semi Bold",
        15,
        22
      ],
      [
        "Body/B1",
        "Regular",
        16,
        24
      ],
      [
        "Body/B2",
        "Medium",
        16,
        24
      ],
      [
        "Body/B3",
        "Regular",
        14,
        20
      ],
      [
        "Body/B4",
        "Medium",
        14,
        20
      ],
      [
        "Caption/C1",
        "Regular",
        12,
        16
      ],
      [
        "Caption/C2",
        "Medium",
        12,
        16
      ],
      [
        "Caption/C3",
        "Medium",
        10,
        14
      ],
      [
        "Label",
        "Medium",
        12,
        16
      ]
    ]
  },
  "secondaryTypography": {
    "headlineLimit": 3
  },
  "radius": [
    4,
    8,
    12,
    16,
    20,
    24,
    28,
    32,
    999
  ],
  "spacing": [
    4,
    8,
    12,
    16,
    20,
    24,
    28,
    32,
    40,
    48
  ],
  "shadow": {
    "styles": {
      "Shadow/S": [
        [
          0,
          1,
          4,
          0,
          0.04
        ],
        [
          0,
          4,
          10,
          0,
          0.06
        ]
      ],
      "Shadow/M": [
        [
          0,
          2,
          16,
          0,
          0.04
        ],
        [
          0,
          8,
          28,
          0,
          0.08
        ]
      ],
      "Shadow/L": [
        [
          0,
          8,
          24,
          0,
          0.06
        ],
        [
          0,
          20,
          56,
          0,
          0.1
        ]
      ]
    }
  }
};
// END GENERATED DESIGN SYSTEM RULES

figma.ui.onmessage = async (message) => {
  if (message.type === "cancel") {
    figma.closePlugin();
    return;
  }

  if (message.type === "pick-selected-color") {
    figma.ui.postMessage({
      type: "picked-color",
      requestId: message.requestId,
      ...readSelectedSolidFill(),
    });
    return;
  }

  if (message.type !== "generate") return;

  let restoreSnapshot = null;

  try {
    const config = normalizeConfig(message.config);
    const issues = [...validateRawInputs(message.config || {}, config), ...validateConfig(config)];
    if (issues.length) {
      figma.ui.postMessage({ type: "error", message: issues.join("\n") });
      return;
    }

    const system = buildSystem(config);
    await preloadFonts(system.textTokens);

    const existing = await scanExisting(system);
    if (existing.total > 0 && !message.confirmedOverwrite) {
      figma.ui.postMessage({
        type: "confirm-overwrite",
        message: `当前文件已有 ${existing.total} 个同名或插件生成的变量 / 样式。是否删除后重新生成？`,
        existing,
      });
      return;
    }

    restoreSnapshot = message.confirmedOverwrite && existing.total > 0 ? await snapshotExisting(existing) : null;
    const pagesToDeleteAfterSuccess = message.confirmedOverwrite && existing.total > 0 ? existing.pages.slice() : [];

    if (message.confirmedOverwrite && existing.total > 0) {
      await deleteExisting(existing, { keepPages: true });
    }

    const result = await writeSystem(system);
    await deletePages(pagesToDeleteAfterSuccess);
    figma.ui.postMessage({ type: "success", message: summarizeResult(result), result });
    figma.notify("Design system generated");
  } catch (error) {
    const messageText = error && error.message ? error.message : String(error);
    const restoreMessage = await restoreAfterFailedOverwrite(restoreSnapshot);
    figma.ui.postMessage({ type: "error", message: `生成失败，已清理本次新建的半成品。${restoreMessage}\n${messageText}` });
  }
};

function readSelectedSolidFill() {
  const selection = figma.currentPage.selection || [];
  if (!selection.length) {
    return {
      ok: false,
      message: "请先在画布中选中一个带纯色填充的图层。",
    };
  }

  const node = selection[0];
  if (!("fills" in node)) {
    return {
      ok: false,
      message: "当前选中图层没有可读取的填充色。请选择一个纯色填充图层。",
    };
  }

  const fills = node.fills;
  if (fills === figma.mixed) {
    return {
      ok: false,
      message: "当前选中图层的填充是混合状态。请选择单个纯色填充图层。",
    };
  }

  if (!Array.isArray(fills) || fills.length === 0) {
    return {
      ok: false,
      message: "当前选中图层没有填充色。请选择一个纯色填充图层。",
    };
  }

  const firstVisibleFill = fills.find((paint) => paint.visible !== false);
  const firstSolidFill = fills.find((paint) => paint.visible !== false && paint.type === "SOLID");
  if (!firstVisibleFill) {
    return {
      ok: false,
      message: "当前选中图层没有可见填充色。请选择一个纯色填充图层。",
    };
  }

  if (!firstSolidFill) {
    return {
      ok: false,
      message: "请选择纯色图层；当前选中图层没有可读取的纯色填充。",
    };
  }

  return {
    ok: true,
    hex: figmaColorToHex(firstSolidFill.color),
  };
}

function normalizeConfig(input) {
  const lightBackgroundInput = normalizeHex(input.lightBackgroundColor, "");
  const darkBackgroundInput = normalizeHex(input.darkBackgroundColor, "");
  const lightDarkBackgrounds = resolveLightDarkBackgrounds(lightBackgroundInput, darkBackgroundInput);
  const config = {
    systemType: input.systemType || "standard",
    multiThemeType: input.multiThemeType || "light-dark",
    primaryKind: input.primaryKind || "solid",
    primaryColor: normalizeHex(input.primaryColor, ""),
    primaryGradient: normalizeGradientInput({
      from: input.primaryGradientFrom,
      to: input.primaryGradientTo,
      fallback: input.primaryGradientFallback,
      direction: input.primaryGradientDirection,
    }),
    lightBackgroundColor: lightDarkBackgrounds.light,
    darkBackgroundColor: lightDarkBackgrounds.dark,
    coolBackgroundColor: normalizeHex(input.coolBackgroundColor, "#F6F9FF"),
    warmBackgroundColor: normalizeHex(input.warmBackgroundColor, "#FFF7F0"),
    themeBackgroundStrategy: input.themeBackgroundStrategy || "shared",
    themes: normalizeThemes(input.themes || []),
    themeColors: [],
	    blackColor: normalizeHex(input.blackColor, ""),
	    primaryFont: String(input.primaryFont || "").trim(),
	    secondaryFonts: normalizeSecondaryFonts(input.secondaryFonts || []),
	    backgroundColor: normalizeHex(input.backgroundColor, ""),
    auxColor: normalizeHex(input.auxColor, ""),
    semanticSet: input.semanticSet || "full",
    neutralMode: input.neutralMode || "solid",
    colorOutput: input.colorOutput || "variable",
    typographyOutput: normalizeTypographyOutput(input.typographyOutput),
    typePreset: input.typePreset || "full",
    visualTemplate: Boolean(input.visualTemplate),
    modules: {
      brand: true,
      neutral: true,
      semantic: input.semanticSet !== "none",
      auxiliary: Boolean(input.auxColor),
      background: Boolean(
        input.backgroundColor ||
          input.lightBackgroundColor ||
          input.darkBackgroundColor ||
          input.coolBackgroundColor ||
          input.warmBackgroundColor ||
          (input.themes || []).some((theme) => theme.backgroundColor),
      ),
      typography: true,
      radius: true,
      spacing: true,
      shadow: true,
    },
  };

  if (config.primaryKind === "gradient" && config.primaryGradient.fallback) {
    config.primaryColor = config.primaryGradient.fallback;
  }

  config.themes = uniquifyThemeNames(config.themes);
  config.themeColors = config.themes.map((theme) => theme.primaryColor).filter(Boolean);

	  if (config.systemType === "lightweight") {
	    config.semanticSet = input.semanticSet || "red-green";
	    config.neutralMode = input.neutralMode || "opacity";
	    config.colorOutput = input.colorOutput || "style";
	    config.typographyOutput = "style";
	    config.typePreset = input.typePreset || "compact";
	    config.secondaryFonts = [];
	  }

  if (config.systemType === "multi-theme" && config.multiThemeType === "multi-primary" && config.themeColors.length) {
    config.primaryColor = config.themeColors[0];
    config.modules.auxiliary = Boolean(config.auxColor) || config.themes.some((theme) => theme.auxiliaryColors.length);
  }

  return config;
}

function normalizeThemes(themes) {
  return themes
    .map((theme, index) => {
      const primaryGradient = normalizeGradientInput({
        from: theme.gradientFrom,
        to: theme.gradientTo,
        fallback: theme.gradientFallback,
        direction: theme.gradientDirection,
      });
      const primaryKind = theme.primaryKind || "solid";
      return {
        name: sanitizeModeName(theme.name || `Theme ${index + 1}`),
        primaryKind,
        primaryColor: primaryKind === "gradient" ? primaryGradient.fallback : normalizeHex(theme.primaryColor, ""),
        primaryGradient,
        backgroundColor: normalizeHex(theme.backgroundColor, ""),
        auxiliaryColors: (theme.auxiliaryColors || [])
          .map((aux, auxIndex) => ({
            name: sanitizeTokenSegment(aux.name || `aux-${auxIndex + 1}`),
            value: normalizeHex(aux.value, ""),
          }))
          .filter((aux) => aux.value),
      };
    })
    .filter((theme) => theme.primaryColor);
}

function normalizeGradientInput(input) {
  return {
    from: normalizeHex(input.from, ""),
    to: normalizeHex(input.to, ""),
    fallback: normalizeHex(input.fallback, ""),
    direction: input.direction || "linear",
  };
		}

function normalizeSecondaryFonts(fonts) {
  return fonts
    .slice(0, 2)
    .map((font) => ({
      family: String(font.family || "").trim(),
      usage: ["none", "headline", "title", "number", "brand"].includes(font.usage) ? font.usage : "none",
    }))
    .filter((font) => font.family && font.usage !== "none");
}

function normalizeTypographyOutput(value) {
  if (value === "variable" || value === "token") return "style";
  if (["style", "token-style"].includes(value)) return value;
  return "style";
}

function validateConfig(config) {
  const issues = [];
  if (config.systemType === "multi-theme" && config.multiThemeType === "multi-primary") {
    if (config.themeColors.length < 2) issues.push("多主色至少需要 2 个主题主色");
    const maxAuxCount = Math.max(0, ...config.themes.map((theme) => theme.auxiliaryColors.length));
    for (let auxIndex = 0; auxIndex < maxAuxCount; auxIndex += 1) {
      const hasAnyAux = config.themes.some((theme) => theme.auxiliaryColors[auxIndex]?.value);
      const hasEveryAux = config.themes.every((theme) => theme.auxiliaryColors[auxIndex]?.value);
      if (hasAnyAux && !hasEveryAux) {
        issues.push(`多主色的辅助色 ${auxIndex + 1} 需要每个主题都填写，才能跟随主题切换`);
      }
    }
  } else if (!config.primaryColor) {
    issues.push("需要主色");
  }
  if (!config.blackColor) issues.push("需要黑色 / Neutral 基准");
  if (config.blackColor === RULES.forbiddenBlack) issues.push("黑色不能使用 #000000");
	  if (!config.primaryFont) issues.push("需要主字体");
	  config.secondaryFonts.forEach((font, index) => {
	    if (!font.family) issues.push(`副字体 ${index + 1} 需要字体名称`);
	  });
	  return issues;
	}

function validateRawInputs(input, config) {
  const issues = [];
  const multiPrimary = config.systemType === "multi-theme" && config.multiThemeType === "multi-primary";
  if (!multiPrimary && input.primaryKind !== "gradient" && input.primaryColor && !hasValidHex(input.primaryColor)) issues.push("主色格式不正确");
  if (!multiPrimary && input.primaryKind === "gradient") {
    validateGradientRaw(input.primaryGradientFrom, input.primaryGradientTo, input.primaryGradientFallback, "主色渐变", issues);
  }
  if (input.blackColor && !hasValidHex(input.blackColor)) issues.push("黑色 / Neutral 基准格式不正确");
  if (input.auxColor && !hasValidHex(input.auxColor)) issues.push("辅助色格式不正确");
  if (input.backgroundColor && !hasValidHex(input.backgroundColor)) issues.push("背景色格式不正确");
  if (input.lightBackgroundColor && !hasValidHex(input.lightBackgroundColor)) issues.push("浅色背景格式不正确");
  if (input.darkBackgroundColor && !hasValidHex(input.darkBackgroundColor)) issues.push("深色背景格式不正确");
  if (input.coolBackgroundColor && !hasValidHex(input.coolBackgroundColor)) issues.push("冷色背景格式不正确");
  if (input.warmBackgroundColor && !hasValidHex(input.warmBackgroundColor)) issues.push("暖色背景格式不正确");
  if (input.themeBackgroundStrategy === "tone-pair" && (input.coolBackgroundColor || input.warmBackgroundColor) && (!input.coolBackgroundColor || !input.warmBackgroundColor)) {
    issues.push("冷暖双背景需要同时填写冷色背景和暖色背景");
  }
  if (multiPrimary) {
    const hasPerThemeBackground = input.themeBackgroundStrategy === "per-theme" && (input.themes || []).some((theme) => theme.backgroundColor);
    (input.themes || []).forEach((theme, index) => {
      if (theme.primaryKind === "gradient") {
        validateGradientRaw(theme.gradientFrom, theme.gradientTo, theme.gradientFallback, `Theme ${index + 1} 主色渐变`, issues);
      } else if (theme.primaryColor && !hasValidHex(theme.primaryColor)) {
        issues.push(`Theme ${index + 1} 主色格式不正确`);
      }
      (theme.auxiliaryColors || []).forEach((aux, auxIndex) => {
        if (aux.value && !hasValidHex(aux.value)) issues.push(`Theme ${index + 1} 辅助色 ${auxIndex + 1} 格式不正确`);
      });
      if (hasPerThemeBackground && !theme.backgroundColor) {
        issues.push(`Theme ${index + 1} 需要背景色`);
      }
      if (theme.backgroundColor && !hasValidHex(theme.backgroundColor)) issues.push(`Theme ${index + 1} 背景色格式不正确`);
    });
  }
  return issues;
}

function validateGradientRaw(from, to, fallback, label, issues) {
  if (!from || !to || !fallback) {
    issues.push(`${label}需要起点、终点和代表主色`);
    return;
  }
  if (!hasValidHex(from)) issues.push(`${label}起点格式不正确`);
  if (!hasValidHex(to)) issues.push(`${label}终点格式不正确`);
  if (!hasValidHex(fallback)) issues.push(`${label}代表主色格式不正确`);
}

async function scanExisting(system) {
  const variables = await getLocalVariables();
  const collections = await getLocalCollections();
  const paintStyles = await getLocalPaintStyles();
  const textStyles = await getLocalTextStyles();
  const effectStyles = await getLocalEffectStyles();
  const pages = figma.root.children.filter((page) => page.name === "Design System");
  const planned = plannedNames(system);

  const matchingVariables = variables.filter((item) => isPluginOwned(item) || planned.variableNames.has(item.name));
  const matchingCollections = collections.filter((item) => item.name === "Design System");
  const matchingPaintStyles = paintStyles.filter((item) => isPluginOwned(item) || planned.paintStyleNames.has(item.name));
  const matchingTextStyles = textStyles.filter((item) => isPluginOwned(item) || planned.textStyleNames.has(item.name));
  const matchingEffectStyles = effectStyles.filter((item) => isPluginOwned(item) || planned.effectStyleNames.has(item.name));

  return {
    variables: matchingVariables,
    collections: matchingCollections,
    paintStyles: matchingPaintStyles,
    textStyles: matchingTextStyles,
    effectStyles: matchingEffectStyles,
    pages,
    total: matchingVariables.length + matchingPaintStyles.length + matchingTextStyles.length + matchingEffectStyles.length + pages.length,
  };
}

async function snapshotExisting(existing) {
  const collections = await getLocalCollections();
  const collectionById = new Map(collections.map((collection) => [collection.id, collection]));
  const collectionIds = new Set(existing.collections.map((collection) => collection.id));
  existing.variables.forEach((variable) => {
    if (variable.variableCollectionId) collectionIds.add(variable.variableCollectionId);
  });

  return {
    collections: collections
      .filter((collection) => collectionIds.has(collection.id))
      .map((collection) => ({
        name: collection.name,
        modes: collection.modes.map((mode) => mode.name),
      })),
    variables: existing.variables.map((variable) => snapshotVariable(variable, collectionById.get(variable.variableCollectionId))),
    paintStyles: existing.paintStyles.map(snapshotPaintStyle),
    textStyles: existing.textStyles.map(snapshotTextStyle),
    effectStyles: existing.effectStyles.map(snapshotEffectStyle),
  };
}

function snapshotVariable(variable, collection) {
  const valuesByModeName = {};
  const modes = collection ? collection.modes : [];
  modes.forEach((mode) => {
    if (variable.valuesByMode && variable.valuesByMode[mode.modeId] !== undefined) {
      valuesByModeName[mode.name] = cloneSnapshotValue(variable.valuesByMode[mode.modeId]);
    }
  });

  return {
    name: variable.name,
    type: variable.resolvedType || "COLOR",
    collectionName: collection ? collection.name : "Design System",
    modes: modes.map((mode) => mode.name),
    valuesByModeName,
  };
}

function snapshotPaintStyle(style) {
  return {
    name: style.name,
    paints: cloneSnapshotValue(style.paints || []),
    description: "description" in style ? String(style.description || "") : "",
  };
}

function snapshotTextStyle(style) {
  return {
    name: style.name,
    fontName: cloneSnapshotValue(style.fontName),
    fontSize: style.fontSize,
    lineHeight: cloneSnapshotValue(style.lineHeight),
    letterSpacing: cloneSnapshotValue(style.letterSpacing),
    paragraphSpacing: style.paragraphSpacing,
    description: "description" in style ? String(style.description || "") : "",
  };
}

function snapshotEffectStyle(style) {
  return {
    name: style.name,
    effects: cloneSnapshotValue(style.effects || []),
    description: "description" in style ? String(style.description || "") : "",
  };
}

function cloneSnapshotValue(value) {
  return value === undefined ? undefined : JSON.parse(JSON.stringify(value));
}

async function restoreAfterFailedOverwrite(snapshot) {
  if (!snapshot) return "";
  try {
    await restoreExistingSnapshot(snapshot);
    return "\n旧变量 / 样式已恢复；旧可视化页已保留。";
  } catch (restoreError) {
    const message = restoreError && restoreError.message ? restoreError.message : String(restoreError);
    return `\n但恢复旧变量 / 样式时失败，请检查文件后再继续：${message}`;
  }
}

async function restoreExistingSnapshot(snapshot) {
  const collectionByName = new Map();
  for (const collectionSnapshot of snapshot.collections) {
    const collection = await getOrCreateCollection(collectionSnapshot.name);
    const modes = syncCollectionModes(collection, collectionSnapshot.modes.length ? collectionSnapshot.modes : ["Default"]);
    collectionByName.set(collectionSnapshot.name, { collection, modes });
  }

  for (const variableSnapshot of snapshot.variables) {
    await restoreVariableSnapshot(variableSnapshot, collectionByName);
  }
  for (const styleSnapshot of snapshot.paintStyles) await restorePaintStyleSnapshot(styleSnapshot);
  for (const styleSnapshot of snapshot.textStyles) await restoreTextStyleSnapshot(styleSnapshot);
  for (const styleSnapshot of snapshot.effectStyles) await restoreEffectStyleSnapshot(styleSnapshot);
}

async function restoreVariableSnapshot(snapshot, collectionByName) {
  let entry = collectionByName.get(snapshot.collectionName);
  if (!entry) {
    const collection = await getOrCreateCollection(snapshot.collectionName);
    const modes = syncCollectionModes(collection, snapshot.modes.length ? snapshot.modes : ["Default"]);
    entry = { collection, modes };
    collectionByName.set(snapshot.collectionName, entry);
  }

  const variable = await createVariable(snapshot.name, entry.collection, snapshot.type, { optional: snapshot.type === "STRING" });
  if (!variable) return;
  markPluginOwned(variable);
  entry.modes.forEach((mode) => {
    const value = snapshot.valuesByModeName[mode.name];
    if (value !== undefined) variable.setValueForMode(mode.modeId, cloneSnapshotValue(value));
  });
}

async function restorePaintStyleSnapshot(snapshot) {
  const style = (await findPaintStyleByName(snapshot.name)) || figma.createPaintStyle();
  style.name = snapshot.name;
  style.paints = cloneSnapshotValue(snapshot.paints || []);
  restoreDescription(style, snapshot.description);
  markPluginOwned(style);
}

async function restoreTextStyleSnapshot(snapshot) {
  const style = (await findTextStyleByName(snapshot.name)) || figma.createTextStyle();
  style.name = snapshot.name;
  if (snapshot.fontName && snapshot.fontName.family && snapshot.fontName.style) {
    try {
      await figma.loadFontAsync(snapshot.fontName);
    } catch (error) {
      // Existing style restoration should remain best-effort if a font disappears.
    }
    style.fontName = snapshot.fontName;
  }
  if (snapshot.fontSize !== undefined) style.fontSize = snapshot.fontSize;
  if (snapshot.lineHeight !== undefined) style.lineHeight = cloneSnapshotValue(snapshot.lineHeight);
  if (snapshot.letterSpacing !== undefined) style.letterSpacing = cloneSnapshotValue(snapshot.letterSpacing);
  if (snapshot.paragraphSpacing !== undefined) style.paragraphSpacing = snapshot.paragraphSpacing;
  restoreDescription(style, snapshot.description);
  markPluginOwned(style);
}

async function restoreEffectStyleSnapshot(snapshot) {
  const style = (await findEffectStyleByName(snapshot.name)) || figma.createEffectStyle();
  style.name = snapshot.name;
  style.effects = cloneSnapshotValue(snapshot.effects || []);
  restoreDescription(style, snapshot.description);
  markPluginOwned(style);
}

function restoreDescription(node, description) {
  if ("description" in node) node.description = String(description || "");
}

async function findPaintStyleByName(name) {
  return (await getLocalPaintStyles()).find((style) => style.name === name);
}

async function findTextStyleByName(name) {
  return (await getLocalTextStyles()).find((style) => style.name === name);
}

async function findEffectStyleByName(name) {
  return (await getLocalEffectStyles()).find((style) => style.name === name);
}

async function deleteExisting(existing, options = {}) {
  existing.variables.forEach((item) => safeRemove(item));
  existing.paintStyles.forEach((item) => safeRemove(item));
  existing.textStyles.forEach((item) => safeRemove(item));
  existing.effectStyles.forEach((item) => safeRemove(item));
  if (!options.keepPages) await deletePages(existing.pages);
}

async function deletePages(pages) {
  for (const page of pages) {
    try {
      if (figma.root.children.length <= 1) return;
      if (figma.currentPage === page) {
        await setCurrentPage(figma.root.children.find((candidate) => candidate !== page));
      }
      safeRemove(page);
    } catch (error) {
      // Keep generation success visible even if an old visual page cannot be removed.
    }
  }
}

	function plannedNames(system) {
	  const numberNames = shouldWriteNumberVariables(system.config) ? [...system.radiusTokens, ...system.spacingTokens].map((token) => token.name) : [];
	  const colorNames = system.colorTokens.map((token) => token.name);
	  const colorVariableNames = system.config.colorOutput === "variable" ? colorNames : [];
	  const paintStyleNames = system.config.colorOutput === "style" ? colorNames : [];
	  const typographyVariableNames = shouldWriteTypographyVariables(system.config) ? typographyVariableNamesForTokens(system.textTokens) : [];
	  const textStyleNames = shouldWriteTextStyles(system.config) ? system.textTokens.map((token) => token.name) : [];
	  return {
	    variableNames: new Set([...colorVariableNames, ...numberNames, ...typographyVariableNames]),
	    paintStyleNames: new Set([...paintStyleNames, ...system.gradientTokens.map((token) => token.name)]),
	    textStyleNames: new Set(textStyleNames),
	    effectStyleNames: new Set(system.shadowTokens.map((token) => token.name)),
	  };
	}

function markPluginOwned(node) {
  if (!node) return;
  if (typeof node.setPluginData === "function") {
    node.setPluginData(PLUGIN_OWNER_KEY, PLUGIN_OWNER_VALUE);
  }
  if ("description" in node) {
    const current = String(node.description || "");
    node.description = current.includes(PLUGIN_DESCRIPTION_MARKER)
      ? current
      : [current, PLUGIN_DESCRIPTION_MARKER].filter(Boolean).join("\n");
  }
}

function trackCreated(kind, node) {
  if (!currentWriteTracker || !node) return;
  currentWriteTracker[kind].push(node);
}

function createWriteTracker() {
  return {
    collections: [],
    variables: [],
    paintStyles: [],
    textStyles: [],
    effectStyles: [],
    pages: [],
  };
}

async function rollbackWriteTracker(tracker) {
  if (!tracker) return;
  tracker.variables.forEach((item) => safeRemove(item));
  tracker.paintStyles.forEach((item) => safeRemove(item));
  tracker.textStyles.forEach((item) => safeRemove(item));
  tracker.effectStyles.forEach((item) => safeRemove(item));
  for (const page of tracker.pages) {
    if (figma.root.children.length <= 1) continue;
    if (figma.currentPage === page) {
      await setCurrentPage(figma.root.children.find((candidate) => candidate !== page));
    }
    safeRemove(page);
  }
  tracker.collections.forEach((item) => safeRemove(item));
}

function safeRemove(node) {
  try {
    if (node && typeof node.remove === "function") node.remove();
  } catch (error) {
    // Keep the original generation error visible.
  }
}

function isPluginOwned(node) {
  return (
    Boolean(node && typeof node.getPluginData === "function" && node.getPluginData(PLUGIN_OWNER_KEY) === PLUGIN_OWNER_VALUE) ||
    Boolean(node && "description" in node && String(node.description || "").includes(PLUGIN_DESCRIPTION_MARKER))
  );
}

async function writeSystem(system) {
  const result = {
    colorVariables: 0,
    colorStyles: 0,
    gradientStyles: 0,
    numberVariables: 0,
    typographyVariables: 0,
    textStyles: 0,
    effectStyles: 0,
    visualNodes: 0,
  };

  currentWriteTracker = createWriteTracker();
  try {
    if (system.config.colorOutput === "variable") {
      result.colorVariables = await writeColorVariables(system.colorTokens, system.colorModes);
    } else {
      result.colorStyles = writePaintStyles(system.colorTokens);
    }
    result.gradientStyles = writeGradientStyles(system.gradientTokens);

    if (shouldWriteNumberVariables(system.config)) {
      result.numberVariables = await writeNumberVariables([...system.radiusTokens, ...system.spacingTokens]);
    }
    if (shouldWriteTypographyVariables(system.config)) {
      result.typographyVariables = await writeTypographyVariables(system.textTokens);
    }
    if (shouldWriteTextStyles(system.config)) {
      result.textStyles = await writeTextStyles(system.textTokens);
    }
    result.effectStyles = writeEffectStyles(system.shadowTokens);

    if (system.config.visualTemplate) {
      result.visualNodes = await createVisualPage(system);
    }
  } catch (error) {
    await rollbackWriteTracker(currentWriteTracker);
    throw error;
  } finally {
    currentWriteTracker = null;
  }

  return result;
}

function shouldWriteNumberVariables(config) {
  return config.systemType !== "lightweight" || config.colorOutput === "variable";
}

function shouldWriteTypographyVariables(config) {
  return config.typographyOutput === "token-style";
}

function shouldWriteTextStyles(config) {
  return config.typographyOutput === "style" || config.typographyOutput === "token-style";
}

async function writeColorVariables(tokens, modeNames) {
  const collection = await getOrCreateCollection("Design System");
  const modes = syncCollectionModes(collection, modeNames);
  let count = 0;
  for (const token of tokens) {
    const variable = await createVariable(token.name, collection, "COLOR");
    modes.forEach((mode) => {
      variable.setValueForMode(mode.modeId, paintToVariableValue(tokenValueForMode(token, mode.name)));
    });
    count += 1;
  }
  return count;
}

function syncCollectionModes(collection, modeNames) {
  const desired = modeNames.length ? modeNames : ["Default"];
  const modes = [...collection.modes];
  if (modes[0] && modes[0].name !== desired[0]) {
    if (typeof collection.renameMode === "function") {
      collection.renameMode(modes[0].modeId, desired[0]);
    }
    modes[0] = { ...modes[0], name: desired[0] };
  }
  desired.slice(1).forEach((name) => {
    if (!modes.some((mode) => mode.name === name)) {
      const modeId = collection.addMode(name);
      modes.push({ modeId, name });
    }
  });
  modes.slice().forEach((mode) => {
    if (!desired.includes(mode.name) && typeof collection.removeMode === "function") {
      collection.removeMode(mode.modeId);
      const index = modes.findIndex((item) => item.modeId === mode.modeId);
      if (index >= 0) modes.splice(index, 1);
    }
  });
  return desired.map((name) => modes.find((mode) => mode.name === name)).filter(Boolean);
}

function tokenValueForMode(token, modeName) {
  if (token.valuesByMode && token.valuesByMode[modeName]) return token.valuesByMode[modeName];
  return { value: token.value, opacity: token.opacity };
}

function setVariableForAllModes(variable, collection, value) {
  collection.modes.forEach((mode) => {
    variable.setValueForMode(mode.modeId, value);
  });
}

async function writeNumberVariables(tokens) {
  const collection = await getOrCreateCollection("Design System");
  const modeId = collection.modes[0].modeId;
  let count = 0;
  for (const token of tokens) {
    const variable = await createVariable(token.name, collection, "FLOAT");
    setVariableForAllModes(variable, collection, token.value);
    count += 1;
  }
  return count;
}

async function writeTypographyVariables(tokens) {
  const collection = await getOrCreateCollection("Design System");
  let count = 0;
  for (const token of tokens) {
    const variables = [
      { name: `Typography/${token.name}/font-family`, value: token.family, type: "STRING" },
      { name: `Typography/${token.name}/font-weight-name`, value: token.weight, type: "STRING" },
      { name: `Typography/${token.name}/font-weight-value`, value: fontWeightValue(token.weight), type: "FLOAT" },
      { name: `Typography/${token.name}/size`, value: token.size },
      { name: `Typography/${token.name}/line`, value: token.line },
      { name: `Typography/${token.name}/spacing`, value: token.spacing || 0 },
    ];
    for (const item of variables) {
      const variable = await createVariable(item.name, collection, item.type || "FLOAT", { optional: item.type === "STRING" });
      if (!variable) continue;
      setVariableForAllModes(variable, collection, item.value);
      count += 1;
    }
  }
  return count;
}

function typographyVariableNamesForTokens(tokens) {
  return tokens.flatMap((token) => [
    `Typography/${token.name}/font-family`,
    `Typography/${token.name}/font-weight-name`,
    `Typography/${token.name}/font-weight-value`,
    `Typography/${token.name}/size`,
    `Typography/${token.name}/line`,
    `Typography/${token.name}/spacing`,
  ]);
}

function writePaintStyles(tokens) {
  let count = 0;
  tokens.forEach((token) => {
    const style = figma.createPaintStyle();
    trackCreated("paintStyles", style);
    style.name = token.name;
    style.paints = [tokenToSolidPaint(token)];
    markPluginOwned(style);
    count += 1;
  });
  return count;
}

function writeGradientStyles(tokens) {
  let count = 0;
  tokens.forEach((token) => {
    const style = figma.createPaintStyle();
    trackCreated("paintStyles", style);
    style.name = token.name;
    style.paints = [gradientToPaint(token)];
    markPluginOwned(style);
    count += 1;
  });
  return count;
}

async function writeTextStyles(tokens) {
  let count = 0;
  for (const token of tokens) {
    const style = figma.createTextStyle();
    trackCreated("textStyles", style);
    style.name = token.name;
    style.fontName = token.resolvedFontName || (await loadFontWithFallback(token.family, token.weight));
    style.fontSize = token.size;
    style.lineHeight = { value: token.line, unit: "PIXELS" };
    style.letterSpacing = { value: token.spacing || 0, unit: "PIXELS" };
    markPluginOwned(style);
    count += 1;
  }
  return count;
}

function writeEffectStyles(tokens) {
  let count = 0;
  tokens.forEach((token) => {
    const style = figma.createEffectStyle();
    trackCreated("effectStyles", style);
    style.name = token.name;
    style.effects = token.layers.map((layer) => ({
      type: "DROP_SHADOW",
      visible: true,
      color: rgbaToFigmaColor(layer.color),
      offset: { x: layer.x, y: layer.y },
      radius: layer.blur,
      spread: layer.spread,
      blendMode: "NORMAL",
    }));
    markPluginOwned(style);
    count += 1;
  });
  return count;
}

function brandTokens(primary) {
  if (!primary) return [];
  return RULES.brand.map((token) => ({
    name: token.name,
    value: token.source ? primary : mix(primary, colorRef(token.mixWith), token.amount),
  }));
}

function buildSystem(config) {
  const colorModes = config.colorOutput === "variable" ? colorModesForConfig(config) : ["Default"];
  const colorTokens = [];
  const colorTokenSource = config.colorOutput === "variable" ? colorVariableTokensForConfig : colorStyleTokensForConfig;
  colorTokens.push(...colorTokenSource(config, colorModes));

  return {
    config,
    colorModes,
    colorTokens,
    gradientTokens: gradientTokensForConfig(config),
    radiusTokens: RULES.radius.map((value) => ({ name: `Radius/${value}px`, value })),
    spacingTokens: RULES.spacing.map((value) => ({ name: `Spacing/${value}px`, value })),
    textTokens: typographyTokens(config),
    shadowTokens: shadowTokens(config),
  };
}

function colorStyleTokensForConfig(config) {
  const colorTokens = [];
  if (config.modules.brand) colorTokens.push(...brandTokensForConfig(config));
  if (config.modules.background) colorTokens.push(...backgroundTokens(config));
  if (config.modules.neutral) colorTokens.push(...neutralTokens(config));
  if (config.modules.semantic) colorTokens.push(...semanticTokens(config));
  if (config.modules.auxiliary) colorTokens.push(...auxiliaryTokensForConfig(config));
  return colorTokens;
}

function colorVariableTokensForConfig(config, modes) {
  const colorTokens = [];
  if (config.modules.brand) colorTokens.push(...brandModeTokens(config, modes));
  if (config.modules.background) colorTokens.push(...backgroundModeTokens(config, modes));
  if (config.modules.neutral) colorTokens.push(...neutralModeTokens(config, modes));
  if (config.modules.semantic) colorTokens.push(...semanticModeTokens(config, modes));
  if (config.modules.auxiliary) colorTokens.push(...auxiliaryModeTokens(config, modes));
  return colorTokens;
}

function colorModesForConfig(config) {
  if (config.systemType === "multi-theme" && config.multiThemeType === "light-dark") return ["Light", "Dark"];
  if (config.systemType === "multi-theme" && config.multiThemeType === "multi-primary") {
    return uniqueNames(config.themes.map((theme, index) => theme.name || `Theme ${index + 1}`));
  }
  return ["Default"];
}

function brandTokensForConfig(config) {
  if (config.systemType === "multi-theme" && config.multiThemeType === "multi-primary") {
    return config.themes.flatMap((theme) => replaceTopPrefix(brandTokens(theme.primaryColor), "Brand", `Brand/${theme.name}`));
  }

  if (config.systemType === "multi-theme" && config.multiThemeType === "light-dark") {
    const darkPrimary = adaptPrimaryForDark(config.primaryColor, config.darkBackgroundColor);
    return [...prefixTokens(brandTokens(config.primaryColor), "Light"), ...prefixTokens(brandTokens(darkPrimary), "Dark")];
  }

  return brandTokens(config.primaryColor);
}

function brandModeTokens(config, modes) {
  if (config.systemType === "multi-theme" && config.multiThemeType === "multi-primary") {
    return modeTokensFromTokenSets(modes.map((mode, index) => [mode, brandTokens(config.themeColors[index] || config.primaryColor)]));
  }
  if (config.systemType === "multi-theme" && config.multiThemeType === "light-dark") {
    const darkPrimary = adaptPrimaryForDark(config.primaryColor, config.darkBackgroundColor);
    return modeTokensFromTokenSets([
      ["Light", brandTokens(config.primaryColor)],
      ["Dark", brandTokens(darkPrimary)],
    ]);
  }
  return brandTokens(config.primaryColor);
}

function gradientTokensForConfig(config) {
  if (config.systemType === "multi-theme" && config.multiThemeType === "multi-primary") {
    return config.themes
      .filter((theme) => theme.primaryKind === "gradient" && theme.primaryGradient.from && theme.primaryGradient.to)
      .map((theme) => ({
        name: `Brand/${theme.name}/primary-gradient`,
        ...theme.primaryGradient,
      }));
  }

  if (config.primaryKind === "gradient" && config.primaryGradient.from && config.primaryGradient.to) {
    if (config.systemType === "multi-theme" && config.multiThemeType === "light-dark") {
      return [
        { name: "Light/Brand/primary-gradient", ...config.primaryGradient },
        { name: "Dark/Brand/primary-gradient", ...adaptGradientForDark(config.primaryGradient, config.darkBackgroundColor) },
      ];
    }
    return [{ name: "Brand/primary-gradient", ...config.primaryGradient }];
  }

  return [];
}

function adaptGradientForDark(gradient, background) {
  return {
    ...gradient,
    from: adaptPrimaryForDark(gradient.from, background),
    to: adaptPrimaryForDark(gradient.to, background),
    fallback: adaptPrimaryForDark(gradient.fallback, background),
  };
}

function backgroundTokens(config) {
  if (config.systemType === "multi-theme" && config.multiThemeType === "light-dark") {
    return [
      { name: "Light/Background/BG", value: config.lightBackgroundColor },
      { name: "Dark/Background/BG", value: config.darkBackgroundColor },
    ];
  }

  if (config.systemType === "multi-theme" && config.multiThemeType === "multi-primary") {
    if (config.themeBackgroundStrategy === "tone-pair") {
      return [
        { name: "Background/Cool/BG", value: config.coolBackgroundColor },
        { name: "Background/Warm/BG", value: config.warmBackgroundColor },
      ];
    }

    if (config.themeBackgroundStrategy === "per-theme") {
      return config.themes
        .filter((theme) => theme.backgroundColor)
        .map((theme) => ({ name: `Background/${theme.name}/BG`, value: theme.backgroundColor }));
    }
  }

  if (!config.backgroundColor) return [];
  return [{ name: "Background/BG", value: config.backgroundColor }];
}

function backgroundModeTokens(config, modes) {
  if (config.systemType === "multi-theme" && config.multiThemeType === "light-dark") {
    return [
      {
        name: "Background/BG",
        value: config.lightBackgroundColor,
        valuesByMode: {
          Light: { value: config.lightBackgroundColor },
          Dark: { value: config.darkBackgroundColor },
        },
      },
    ];
  }
  if (config.systemType === "multi-theme" && config.multiThemeType === "multi-primary") {
    if (config.themeBackgroundStrategy === "tone-pair") {
      const valuesByMode = Object.fromEntries(
        modes.map((mode, index) => {
          const theme = config.themes[index] || config.themes[0];
          return [mode, { value: backgroundValueForTheme(theme, config) }];
        }),
      );
      return [
        {
          name: "Background/BG",
          value: backgroundValueForTheme(config.themes[0], config),
          valuesByMode,
          visualModeGroups: [
            { name: "Cool", value: config.coolBackgroundColor },
            { name: "Warm", value: config.warmBackgroundColor },
          ],
        },
      ];
    }

    if (config.themeBackgroundStrategy === "per-theme") {
      const valuesByMode = Object.fromEntries(
        modes.map((mode, index) => {
          const theme = config.themes[index] || config.themes[0];
          return [mode, { value: backgroundValueForTheme(theme, config) }];
        }),
      );
      return [
        {
          name: "Background/BG",
          value: backgroundValueForTheme(config.themes[0], config),
          valuesByMode,
        },
      ];
    }
  }
  if (!config.backgroundColor) return [];
  return sameValueModeTokens([{ name: "Background/BG", value: config.backgroundColor }], modes);
}

function backgroundValueForTheme(theme, config) {
  if (!theme) return config.backgroundColor || config.coolBackgroundColor || config.warmBackgroundColor;
  if (config.themeBackgroundStrategy === "per-theme") return theme.backgroundColor || config.backgroundColor;
  if (config.themeBackgroundStrategy === "tone-pair") {
    return backgroundToneForColor(theme.primaryColor) === "warm" ? config.warmBackgroundColor : config.coolBackgroundColor;
  }
  return config.backgroundColor;
}

function backgroundToneForColor(hex) {
  const hue = hexToHsl(hex).h;
  return hue < 90 || hue >= 300 ? "warm" : "cool";
}

function resolveLightDarkBackgrounds(lightInput, darkInput) {
  const fallbackLight = "#F7F8FA";
  const fallbackDark = deriveDarkBackground(fallbackLight);
  if (lightInput && darkInput) return { light: lightInput, dark: darkInput };
  if (lightInput) return { light: lightInput, dark: deriveDarkBackground(lightInput) };
  if (darkInput) return { light: deriveLightBackground(darkInput), dark: darkInput };
  return { light: fallbackLight, dark: fallbackDark };
}

function deriveDarkBackground(lightHex) {
  const rule = RULES.lightDark.backgroundToneMapping.darkFromLight;
  const tone = hexToOklch(lightHex);
  const sourceLightness = clamp(tone.l, 0.88, 0.99);
  const targetLightness = clamp(rule.baseLightness + (0.99 - sourceLightness) * rule.sourceLightnessInfluence, rule.minLightness, rule.maxLightness);
  const targetChroma = clamp(tone.c * rule.chromaMultiplier, 0, rule.maxChroma);
  return oklchToHex({ l: targetLightness, c: targetChroma, h: tone.h });
}

function deriveLightBackground(darkHex) {
  const rule = RULES.lightDark.backgroundToneMapping.lightFromDark;
  const tone = hexToOklch(darkHex);
  const sourceLightness = clamp(tone.l, 0.08, 0.28);
  const targetLightness = clamp(rule.baseLightness - (sourceLightness - 0.08) * rule.sourceLightnessInfluence, rule.minLightness, rule.maxLightness);
  const targetChroma = clamp(tone.c * rule.chromaMultiplier, 0, rule.maxChroma);
  return oklchToHex({ l: targetLightness, c: targetChroma, h: tone.h });
}

function prefixTokens(tokens, prefix) {
  return tokens.map((token) => ({ ...token, name: `${prefix}/${token.name}` }));
}

function replaceTopPrefix(tokens, from, to) {
  return tokens.map((token) => ({ ...token, name: token.name.replace(new RegExp(`^${from}/`), `${to}/`) }));
}

function neutralTokens(config) {
  if (config.systemType === "multi-theme" && config.multiThemeType === "light-dark" && config.neutralMode === "solid") {
    const lightNeutral = solidNeutralTokens(config.blackColor);
    const darkNeutral = solidNeutralTokens(mix(RULES.white, RULES.darkAnchor, 0.82));
    return [...prefixTokens(lightNeutral, "Light"), ...prefixTokens(darkNeutral, "Dark")];
  }

  if (config.neutralMode === "solid") {
    return solidNeutralTokens(config.blackColor);
  }

  const blackSteps = config.systemType === "lightweight" ? RULES.neutral.lightweightBlackOverlay : RULES.neutral.standardOverlay;
  const whiteSteps = config.systemType === "lightweight" ? RULES.neutral.lightweightWhiteOverlay : RULES.neutral.standardOverlay;
  return [
    ...blackSteps.map((step) => ({ name: `Overlay/Black/${step}%`, value: config.blackColor, opacity: step / 100 })),
    ...whiteSteps.map((step) => ({ name: `Overlay/White/${step}%`, value: RULES.white, opacity: step / 100 })),
  ];
}

function neutralModeTokens(config, modes) {
  if (config.neutralMode === "solid" && config.systemType === "multi-theme" && config.multiThemeType === "light-dark") {
    const lightNeutral = solidNeutralTokens(config.blackColor);
    const darkNeutral = solidNeutralTokens(mix(RULES.white, RULES.darkAnchor, 0.82));
    return modeTokensFromTokenSets([
      ["Light", lightNeutral],
      ["Dark", darkNeutral],
    ]);
  }
  return sameValueModeTokens(neutralTokens(config), modes);
}

function solidNeutralTokens(base) {
  return RULES.neutral.solidLevels.map((level, index) => ({
    name: `Neutral/${level}`,
    value: index === 0 ? base : index === RULES.neutral.solidLevels.length - 1 ? RULES.white : mix(base, RULES.white, RULES.neutral.solidMix[index]),
  }));
}

function semanticTokens(config) {
  const mode = config.semanticSet;
  if (mode === "none") return [];
  if (config.systemType === "multi-theme" && config.multiThemeType === "light-dark") {
    const darkPrimary = adaptPrimaryForDark(config.primaryColor, config.darkBackgroundColor);
    return [
      ...prefixTokens(semanticTokensForTone(mode, hexToHsl(config.primaryColor)), "Light"),
      ...prefixTokens(semanticTokensForTone(mode, hexToHsl(darkPrimary)), "Dark"),
    ];
  }

  const tone =
    config.systemType === "multi-theme" && config.multiThemeType === "multi-primary"
      ? averageTone(config.themeColors)
      : hexToHsl(config.primaryColor);
  return semanticTokensForTone(mode, tone);
}

function semanticModeTokens(config, modes) {
  const mode = config.semanticSet;
  if (mode === "none") return [];
  if (config.systemType === "multi-theme" && config.multiThemeType === "light-dark") {
    const darkPrimary = adaptPrimaryForDark(config.primaryColor, config.darkBackgroundColor);
    return modeTokensFromTokenSets([
      ["Light", semanticTokensForTone(mode, hexToHsl(config.primaryColor))],
      ["Dark", semanticTokensForTone(mode, hexToHsl(darkPrimary))],
    ]);
  }
  return sameValueModeTokens(semanticTokens(config), modes);
}

function semanticTokensForTone(mode, tone) {
  return RULES.semantic.baseColors
    .filter((item) => item.groups.includes(mode))
    .flatMap((item) => {
      const tuned = tuneSemanticColor(item.value, tone, item);
      return [
        { name: item.name, value: tuned },
        { name: `${item.name}-10%`, value: tuned, opacity: RULES.semantic.tintOpacity },
      ];
    });
}

function averageTone(colors) {
  const tones = colors.map(hexToHsl);
  return tones.reduce(
    (total, tone, index, list) => ({
      s: total.s + tone.s / list.length,
      l: total.l + tone.l / list.length,
    }),
    { s: 0, l: 0 },
  );
}

function adaptPrimaryForDark(primary, background) {
  const primaryTone = hexToHsl(primary);
  const backgroundTone = hexToHsl(background);
  const targetLightness = clamp(Math.max(primaryTone.l, 0.65 + clamp((0.18 - backgroundTone.l) * 0.22, 0, 0.08)), 0.65, 0.78);
  const targetSaturation = Math.min(primaryTone.s, 0.72);
  return hslToHex({ h: primaryTone.h, s: targetSaturation, l: targetLightness });
}

function tuneSemanticColor(base, themeTone, semanticRule) {
  const baseTone = hexToHsl(base);
  const guard = semanticRule.toneGuard || {};
  const saturation = clamp(baseTone.s + (themeTone.s - baseTone.s) * RULES.semantic.toneFollow.saturation, guard.minSaturation || 0, guard.maxSaturation || 1);
  const lightness = clamp(baseTone.l + (themeTone.l - baseTone.l) * RULES.semantic.toneFollow.lightness, guard.minLightness || 0, guard.maxLightness || 1);
  return hslToHex({ h: baseTone.h, s: saturation, l: lightness });
}

function auxiliaryTokens(aux) {
  return RULES.auxiliary.map((token) => ({
    name: token.name,
    value: token.source ? aux : mix(aux, colorRef(token.mixWith), token.amount),
  }));
}

function auxiliaryTokensForConfig(config) {
  if (config.systemType === "multi-theme" && config.multiThemeType === "multi-primary") {
    const sharedTokens = config.auxColor ? auxiliaryTokens(config.auxColor) : [];
    const themeTokens = config.themes.flatMap((theme) =>
      theme.auxiliaryColors.flatMap((aux) =>
        replaceTopPrefix(auxiliaryTokens(aux.value), "Auxiliary", `Auxiliary/${theme.name}/${aux.name}`),
      ),
    );
    return [...sharedTokens, ...themeTokens];
  }
  if (config.systemType === "multi-theme" && config.multiThemeType === "light-dark") {
    return [
      ...prefixTokens(auxiliaryTokens(config.auxColor), "Light"),
      ...prefixTokens(auxiliaryTokens(adaptAuxiliaryForDark(config.auxColor, config.darkBackgroundColor)), "Dark"),
    ];
  }

  return auxiliaryTokens(config.auxColor);
}

function auxiliaryModeTokens(config, modes) {
  if (config.systemType === "multi-theme" && config.multiThemeType === "multi-primary") {
    const sharedTokens = config.auxColor ? sameValueModeTokens(auxiliaryTokens(config.auxColor), modes) : [];
    return [...sharedTokens, ...perThemeAuxiliaryModeTokens(config, modes)];
  }
  if (config.systemType === "multi-theme" && config.multiThemeType === "light-dark") {
    return modeTokensFromTokenSets([
      ["Light", auxiliaryTokens(config.auxColor)],
      ["Dark", auxiliaryTokens(adaptAuxiliaryForDark(config.auxColor, config.darkBackgroundColor))],
    ]);
  }
  return sameValueModeTokens(auxiliaryTokens(config.auxColor), modes);
}

function adaptAuxiliaryForDark(aux, background) {
  return adaptPrimaryForDark(aux, background);
}

function perThemeAuxiliaryModeTokens(config, modes) {
  const maxAuxCount = Math.max(0, ...config.themes.map((theme) => theme.auxiliaryColors.length));
  const tokens = [];
  for (let auxIndex = 0; auxIndex < maxAuxCount; auxIndex += 1) {
    const slotName = `aux-${auxIndex + 1}`;
    const modeTokenSets = modes.map((modeName, themeIndex) => {
      const theme = config.themes[themeIndex] || config.themes[0];
      const auxValue = theme?.auxiliaryColors?.[auxIndex]?.value;
      if (!auxValue) return [modeName, []];
      return [modeName, replaceTopPrefix(auxiliaryTokens(auxValue), "Auxiliary", `Auxiliary/${slotName}`)];
    });
    tokens.push(...modeTokensFromTokenSets(modeTokenSets));
  }
  return tokens;
}

function modeTokensFromTokenSets(modeTokenSets) {
  const byName = new Map();
  modeTokenSets.forEach(([modeName, tokens]) => {
    tokens.forEach((token) => {
      if (!byName.has(token.name)) byName.set(token.name, { name: token.name, value: token.value, opacity: token.opacity, valuesByMode: {} });
      byName.get(token.name).valuesByMode[modeName] = { value: token.value, opacity: token.opacity };
    });
  });
  return Array.from(byName.values()).map((token) => {
    const first = Object.values(token.valuesByMode)[0];
    return { ...token, value: first.value, opacity: first.opacity };
  });
}

function sameValueModeTokens(tokens, modes) {
  if (modes.length <= 1) return tokens;
  return tokens.map((token) => ({
    ...token,
    valuesByMode: Object.fromEntries(modes.map((mode) => [mode, { value: token.value, opacity: token.opacity }])),
  }));
}

	function typographyTokens(config) {
	  const preset = RULES.typography[config.typePreset] || RULES.typography.compact;
	  const primaryTokens = preset.map(([name, weight, size, line]) => ({
	    name,
	    family: config.primaryFont,
	    weight,
	    size,
	    line,
	    spacing: 0,
	  }));
	  if (config.systemType === "lightweight") return primaryTokens;
	  return [...primaryTokens, ...config.secondaryFonts.flatMap((font, index) => secondaryTypographyTokens(font, index, preset))];
	}

	function secondaryTypographyTokens(font, index, preset) {
	  const prefix = `Secondary/${index + 1}`;
	  if (font.usage === "headline") {
	    return preset
	      .filter(([name]) => name.startsWith("Headline"))
	      .slice(0, RULES.secondaryTypography.headlineLimit)
	      .map(([name, weight, size, line]) => secondaryToken(`${prefix}/${name}`, font.family, weight, size, line));
	  }
	  if (font.usage === "title") {
	    const source = preset.find(([name]) => name === "Title") || preset.find(([name]) => name.startsWith("Headline"));
	    return source ? [secondaryToken(`${prefix}/Title`, font.family, source[1], source[2], source[3])] : [];
	  }
	  if (font.usage === "number") {
	    const large = preset.find(([name]) => name === "Headline/H3") || preset.find(([name]) => name.startsWith("Headline"));
	    const small = preset.find(([name]) => name.includes("Body")) || preset.find(([name]) => name === "Body");
	    return [
	      large ? secondaryToken(`${prefix}/Number/Large`, font.family, "Medium", large[2], large[3]) : null,
	      small ? secondaryToken(`${prefix}/Number/Small`, font.family, "Medium", small[2], small[3]) : null,
	    ].filter(Boolean);
	  }
	  const source = preset.find(([name]) => name === "Title") || preset.find(([name]) => name.startsWith("Headline"));
	  return source ? [secondaryToken(`${prefix}/Brand`, font.family, source[1], source[2], source[3])] : [];
	}

	function secondaryToken(name, family, weight, size, line) {
	  return {
	    name,
	    family,
	    weight,
	    size: size + 2,
	    line,
	    spacing: 0,
	  };
	}

function shadowTokens(config) {
  const source = mix(config.blackColor, RULES.darkAnchor, 0.12);
  return Object.entries(RULES.shadow.styles).map(([name, layers]) => ({
    name,
    layers: layers.map(([x, y, blur, spread, opacity]) => ({
      x,
      y,
      blur,
      spread,
      color: rgbaString(source, opacity),
    })),
  }));
}

async function createVisualPage(system) {
  const page = figma.createPage();
  trackCreated("pages", page);
  page.name = "Design System";
  markPluginOwned(page);
  await setCurrentPage(page);
  const fonts = await visualFonts();

  const frame = figma.createFrame();
  frame.name = "Design System";
  markPluginOwned(frame);
  frame.layoutMode = "VERTICAL";
  frame.itemSpacing = 28;
  frame.paddingTop = 64;
  frame.paddingRight = 64;
  frame.paddingBottom = 64;
  frame.paddingLeft = 64;
  frame.resize(1440, 100);
  frame.counterAxisSizingMode = "FIXED";
  frame.primaryAxisSizingMode = "AUTO";
  frame.fills = [{ type: "SOLID", color: hexToFigmaRgb("#F5F7FA") }];
  page.appendChild(frame);

  await appendVisualHero(frame, system, fonts);
  await appendColorSection(frame, system, fonts);
  await appendTypographySection(frame, system.textTokens, fonts);
  await appendMetricsSection(frame, system, fonts);
  frame.counterAxisSizingMode = "FIXED";
  frame.primaryAxisSizingMode = "AUTO";
  figma.viewport.scrollAndZoomIntoView([frame]);
  return frame.findAll().length + 1;
}

function visualColorTokens(system) {
  const tokens = [];
  system.colorTokens.forEach((token) => {
    if (token.visualModeGroups) {
      token.visualModeGroups.forEach((group) => {
        tokens.push({ ...token, value: group.value, opacity: group.opacity, name: insertTokenSegment(token.name, group.name) });
      });
      return;
    }
    if (!token.valuesByMode || system.colorModes.length <= 1) {
      tokens.push(token);
      return;
    }
    if (modeValuesAreIdentical(token, system.colorModes)) {
      tokens.push(token);
      return;
    }
    system.colorModes.forEach((modeName) => {
      const value = tokenValueForMode(token, modeName);
      tokens.push({ ...token, ...value, name: `${modeName}/${token.name}` });
    });
  });
  return [...tokens, ...system.gradientTokens];
}

function insertTokenSegment(name, segment) {
  const parts = String(name || "").split("/");
  if (parts.length < 2) return `${segment}/${name}`;
  return [parts[0], segment, ...parts.slice(1)].join("/");
}

function modeValuesAreIdentical(token, modes) {
  if (!token.valuesByMode || modes.length <= 1) return true;
  const first = visualModeValueKey(token, modes[0]);
  return modes.every((modeName) => visualModeValueKey(token, modeName) === first);
}

function visualModeValueKey(token, modeName) {
  const value = tokenValueForMode(token, modeName);
  return `${value.value || ""}|${value.opacity ?? ""}`;
}

async function visualFonts() {
  return {
    regular: await loadFontWithFallback("Inter", "Regular"),
    medium: await loadFontWithFallback("Inter", "Medium"),
    semiBold: await loadFontWithFallback("Inter", "Semi Bold"),
  };
}

async function appendVisualHero(parent, system, fonts) {
  const hero = visualFrame("Header", "HORIZONTAL", 1312);
  hero.paddingTop = 32;
  hero.paddingRight = 36;
  hero.paddingBottom = 32;
  hero.paddingLeft = 36;
  hero.itemSpacing = 24;
  hero.counterAxisAlignItems = "CENTER";
  hero.fills = [{ type: "SOLID", color: hexToFigmaRgb("#111827") }];
  hero.cornerRadius = 24;
  parent.appendChild(hero);

  const copy = visualFrame("Header Copy", "VERTICAL", 880);
  copy.itemSpacing = 8;
  copy.fills = [];
  hero.appendChild(copy);

  copy.appendChild(visualText("Design System", fonts.semiBold, 40, 48, "#FFFFFF", 860));
  copy.appendChild(
    visualText(
      `${system.config.systemType} foundations · ${system.colorTokens.length} colors · ${system.textTokens.length} text styles`,
      fonts.medium,
      15,
      22,
      "#AAB2C0",
      860,
    ),
  );

  const badges = visualFrame("System Badges", "HORIZONTAL", 330);
  badges.itemSpacing = 10;
  badges.layoutWrap = "WRAP";
  badges.counterAxisSpacing = 10;
  badges.fills = [];
  hero.appendChild(badges);
  ["Color", "Typography", "Effects", "Spacing"].forEach((item) => {
    badges.appendChild(visualBadge(item, fonts.medium));
  });
}

function visualBadge(text, fontName) {
  const badge = visualFrame(text, "HORIZONTAL", 120);
  badge.counterAxisSizingMode = "AUTO";
  badge.primaryAxisSizingMode = "AUTO";
  badge.paddingTop = 8;
  badge.paddingRight = 12;
  badge.paddingBottom = 8;
  badge.paddingLeft = 12;
  badge.cornerRadius = 999;
  badge.fills = [{ type: "SOLID", color: { r: 1, g: 1, b: 1 }, opacity: 0.1 }];
  badge.appendChild(visualText(text, fontName, 13, 18, "#FFFFFF"));
  return badge;
}

function visualText(text, fontName, size, line, color, width) {
  const node = figma.createText();
  node.name = text;
  node.fontName = fontName;
  node.characters = text;
  node.fontSize = size;
  node.lineHeight = { value: line, unit: "PIXELS" };
  node.fills = [{ type: "SOLID", color: hexToFigmaRgb(color) }];
  if (width) {
    node.textAutoResize = "HEIGHT";
    node.resize(width, line);
  }
  return node;
}

async function appendColorSection(parent, system, fonts) {
  const section = visualPanel("Colors", fonts, "Token palettes grouped by role");
  parent.appendChild(section);
  const tokens = visualColorTokens(system);
  if (system.config.systemType === "multi-theme" && system.config.multiThemeType === "light-dark") {
    appendLightDarkColorGroups(section, tokens, fonts);
    return;
  }
  const groups = groupColorTokens(tokens);
  Object.entries(groups).forEach(([name, groupTokens]) => {
    section.appendChild(colorGroup(name, groupTokens, fonts));
  });
}

function appendLightDarkColorGroups(section, tokens, fonts) {
  const lightTokens = [];
  const darkTokens = [];
  const sharedTokens = [];
  tokens.forEach((token) => {
    if (token.name.startsWith("Light/")) {
      lightTokens.push({ ...token, displayName: token.name.replace(/^Light\//, "") });
      return;
    }
    if (token.name.startsWith("Dark/")) {
      darkTokens.push({ ...token, displayName: token.name.replace(/^Dark\//, "") });
      return;
    }
    sharedTokens.push(token);
  });
  section.appendChild(colorModeGroup("Light Theme", lightTokens, fonts));
  section.appendChild(colorModeGroup("Dark Theme", darkTokens, fonts));
  if (sharedTokens.length) section.appendChild(colorModeGroup("Shared", sharedTokens, fonts));
}

function colorModeGroup(name, tokens, fonts) {
  const wrapper = visualFrame(name, "VERTICAL", 1184);
  wrapper.itemSpacing = 18;
  wrapper.paddingTop = 24;
  wrapper.paddingRight = 24;
  wrapper.paddingBottom = 24;
  wrapper.paddingLeft = 24;
  wrapper.cornerRadius = 18;
  wrapper.strokes = [{ type: "SOLID", color: hexToFigmaRgb("#E4E7EC") }];
  wrapper.fills = [{ type: "SOLID", color: hexToFigmaRgb("#F9FAFB") }];

  const header = visualFrame(`${name} Header`, "HORIZONTAL", 1136);
  header.itemSpacing = 8;
  header.counterAxisAlignItems = "CENTER";
  header.fills = [];
  header.appendChild(visualText(name, fonts.semiBold, 22, 30, "#111827"));
  header.appendChild(visualText(`${tokens.length} tokens`, fonts.medium, 13, 18, "#667085"));
  wrapper.appendChild(header);

  const groups = groupColorTokens(tokens);
  Object.entries(groups).forEach(([groupName, groupTokens]) => {
    wrapper.appendChild(colorGroup(groupName, groupTokens, fonts, 1136));
  });
  return wrapper;
}

function colorGroup(name, tokens, fonts, width = 1184) {
  const group = visualFrame(name, "VERTICAL", width);
  group.itemSpacing = 14;
  group.paddingTop = 18;
  group.paddingRight = 0;
  group.paddingBottom = 20;
  group.paddingLeft = 0;
  group.fills = [];

  const header = visualFrame(`${name} Header`, "HORIZONTAL", width);
  header.itemSpacing = 8;
  header.counterAxisAlignItems = "CENTER";
  header.fills = [];
  header.appendChild(visualText(name, fonts.semiBold, 18, 24, "#1F2937"));
  header.appendChild(visualText(`${tokens.length} tokens`, fonts.medium, 13, 18, "#667085"));
  group.appendChild(header);

  const grid = visualFrame(`${name} Palette`, "HORIZONTAL", width);
  grid.layoutWrap = "WRAP";
  grid.itemSpacing = 14;
  grid.counterAxisSpacing = 14;
  grid.primaryAxisSizingMode = "FIXED";
  grid.fills = [];
  group.appendChild(grid);

  tokens.forEach((token) => grid.appendChild(colorSwatchCard(token, fonts)));
  return group;
}

function colorSwatchCard(token, fonts) {
  const card = visualFrame(token.name, "VERTICAL", 174);
  card.paddingTop = 0;
  card.paddingRight = 0;
  card.paddingBottom = 12;
  card.paddingLeft = 0;
  card.itemSpacing = 10;
  card.cornerRadius = 14;
  card.strokes = [{ type: "SOLID", color: hexToFigmaRgb("#E4E7EC") }];
  card.fills = [{ type: "SOLID", color: hexToFigmaRgb("#FFFFFF") }];

  const swatchWrap = visualFrame("Color", "VERTICAL", 174);
  swatchWrap.resize(174, 92);
  swatchWrap.cornerRadius = 14;
  swatchWrap.fills = [{ type: "SOLID", color: hexToFigmaRgb("#F2F4F7") }];
  const swatch = figma.createRectangle();
  swatch.name = "Fill";
  swatch.resize(174, 92);
  swatch.fills = [token.from && token.to ? gradientToPaint(token) : tokenToSolidPaint(token)];
  swatchWrap.appendChild(swatch);
  card.appendChild(swatchWrap);

  const copy = visualFrame("Details", "VERTICAL", 150);
  copy.itemSpacing = 2;
  copy.paddingRight = 12;
  copy.paddingLeft = 12;
  copy.fills = [];
  copy.appendChild(visualText(shortTokenName(token.displayName || token.name), fonts.semiBold, 12, 16, "#1F2937", 150));
  copy.appendChild(visualText(token.value || `${token.from} -> ${token.to}`, fonts.medium, 11, 16, "#7A8493", 150));
  card.appendChild(copy);
  return card;
}

async function appendTypographySection(parent, tokens, fonts) {
  const section = visualPanel("Typography", fonts, "Text styles with live font previews");
  parent.appendChild(section);

  const table = visualFrame("Typography Table", "VERTICAL", 1184);
  table.itemSpacing = 0;
  table.cornerRadius = 16;
  table.clipsContent = true;
  table.strokes = [{ type: "SOLID", color: hexToFigmaRgb("#E4E7EC") }];
  table.fills = [{ type: "SOLID", color: hexToFigmaRgb("#FFFFFF") }];
  section.appendChild(table);
  table.appendChild(typographyHeader(fonts));

  tokens.forEach((token, index) => {
    table.appendChild(typographyRow(token, fonts, index === tokens.length - 1));
  });
}

function typographyHeader(fonts) {
  const row = visualFrame("Table Header", "HORIZONTAL", 1184);
  row.paddingTop = 14;
  row.paddingRight = 22;
  row.paddingBottom = 14;
  row.paddingLeft = 22;
  row.itemSpacing = 20;
  row.fills = [{ type: "SOLID", color: hexToFigmaRgb("#F9FAFB") }];
  row.appendChild(visualText("Style", fonts.semiBold, 12, 16, "#667085", 190));
  row.appendChild(visualText("Preview", fonts.semiBold, 12, 16, "#667085", 590));
  row.appendChild(visualText("Weight", fonts.semiBold, 12, 16, "#667085", 130));
  row.appendChild(visualText("Size", fonts.semiBold, 12, 16, "#667085", 80));
  row.appendChild(visualText("Line", fonts.semiBold, 12, 16, "#667085", 80));
  return row;
}

function typographyRow(token, fonts, isLast) {
  const row = visualFrame(token.name, "HORIZONTAL", 1184);
  row.paddingTop = 18;
  row.paddingRight = 22;
  row.paddingBottom = 18;
  row.paddingLeft = 22;
  row.itemSpacing = 20;
  row.counterAxisAlignItems = "CENTER";
  row.strokes = isLast ? [] : [{ type: "SOLID", color: hexToFigmaRgb("#EAECF0") }];
  row.strokeBottomWeight = isLast ? 0 : 1;
  row.fills = [{ type: "SOLID", color: hexToFigmaRgb("#FFFFFF") }];

  row.appendChild(visualText(token.name, fonts.semiBold, 14, 20, "#1F2937", 190));
  row.appendChild(visualText("Whereas recognition of the inherent dignity 0123456789", token.resolvedFontName, token.size, token.line, "#1F2937", 590));
  row.appendChild(visualText(token.weight, fonts.medium, 13, 18, "#667085", 130));
  row.appendChild(visualText(String(token.size), fonts.medium, 13, 18, "#667085", 80));
  row.appendChild(visualText(String(token.line), fonts.medium, 13, 18, "#667085", 80));
  return row;
}

async function appendMetricsSection(parent, system, fonts) {
  const section = visualPanel("Metrics", fonts, "Radius, spacing, and elevation foundations");
  parent.appendChild(section);

  const grid = visualFrame("Metrics Grid", "HORIZONTAL", 1184);
  grid.itemSpacing = 16;
  grid.fills = [];
  section.appendChild(grid);
  grid.appendChild(metricCard("Radius", system.radiusTokens, fonts, radiusMetric));
  grid.appendChild(metricCard("Spacing", system.spacingTokens, fonts, spacingMetric));
  grid.appendChild(shadowMetricCard("Shadow", system.shadowTokens, fonts));
}

function metricCard(title, tokens, fonts, renderer) {
  const card = visualFrame(title, "VERTICAL", 384);
  card.itemSpacing = 14;
  card.paddingTop = 22;
  card.paddingRight = 22;
  card.paddingBottom = 22;
  card.paddingLeft = 22;
  card.cornerRadius = 16;
  card.strokes = [{ type: "SOLID", color: hexToFigmaRgb("#E4E7EC") }];
  card.fills = [{ type: "SOLID", color: hexToFigmaRgb("#FFFFFF") }];
  card.appendChild(visualText(title, fonts.semiBold, 18, 24, "#1F2937", 330));
  const list = visualFrame(`${title} List`, "VERTICAL", 330);
  list.itemSpacing = 10;
  list.fills = [];
  card.appendChild(list);
  tokens.forEach((token) => list.appendChild(renderer(token, fonts)));
  return card;
}

function radiusMetric(token, fonts) {
  const row = visualFrame(token.name, "HORIZONTAL", 330);
  row.counterAxisAlignItems = "CENTER";
  row.itemSpacing = 12;
  row.fills = [];
  const sample = figma.createRectangle();
  sample.name = "Radius Sample";
  sample.resize(42, 28);
  sample.cornerRadius = Math.min(token.value, 18);
  sample.fills = [{ type: "SOLID", color: hexToFigmaRgb("#EEF2FF") }];
  sample.strokes = [{ type: "SOLID", color: hexToFigmaRgb("#BFD0FF") }];
  row.appendChild(sample);
  row.appendChild(visualText(token.name, fonts.medium, 13, 18, "#475467", 250));
  return row;
}

function spacingMetric(token, fonts) {
  const row = visualFrame(token.name, "HORIZONTAL", 330);
  row.counterAxisAlignItems = "CENTER";
  row.itemSpacing = 12;
  row.fills = [];
  const sample = figma.createRectangle();
  sample.name = "Spacing Sample";
  sample.resize(Math.max(8, Math.min(token.value * 2, 96)), 10);
  sample.cornerRadius = 999;
  sample.fills = [{ type: "SOLID", color: hexToFigmaRgb("#84CAFF") }];
  row.appendChild(sample);
  row.appendChild(visualText(token.name, fonts.medium, 13, 18, "#475467", 210));
  return row;
}

function shadowMetricCard(title, tokens, fonts) {
  const card = metricCard(title, [], fonts, () => null);
  const list = card.children.find((child) => child.name === `${title} List`);
  tokens.forEach((token) => list.appendChild(shadowMetric(token, fonts)));
  return card;
}

function shadowMetric(token, fonts) {
  const row = visualFrame(token.name, "HORIZONTAL", 330);
  row.counterAxisAlignItems = "CENTER";
  row.itemSpacing = 14;
  row.fills = [];
  const sample = figma.createRectangle();
  sample.name = "Shadow Sample";
  sample.resize(44, 44);
  sample.cornerRadius = 12;
  sample.fills = [{ type: "SOLID", color: hexToFigmaRgb("#FFFFFF") }];
  sample.effects = token.layers.map((layer) => ({
    type: "DROP_SHADOW",
    visible: true,
    color: rgbaToFigmaColor(layer.color),
    offset: { x: layer.x, y: layer.y },
    radius: layer.blur,
    spread: layer.spread,
    blendMode: "NORMAL",
  }));
  row.appendChild(sample);
  row.appendChild(visualText(token.name, fonts.medium, 13, 18, "#475467", 250));
  return row;
}

function visualPanel(title, fonts, subtitle) {
  const panel = visualFrame(title, "VERTICAL", 1312);
  panel.itemSpacing = 24;
  panel.paddingTop = 34;
  panel.paddingRight = 36;
  panel.paddingBottom = 36;
  panel.paddingLeft = 36;
  panel.cornerRadius = 24;
  panel.strokes = [{ type: "SOLID", color: hexToFigmaRgb("#E4E7EC") }];
  panel.fills = [{ type: "SOLID", color: hexToFigmaRgb("#FFFFFF") }];
  const header = visualFrame(`${title} Header`, "VERTICAL", 1184);
  header.itemSpacing = 6;
  header.fills = [];
  header.appendChild(visualText(title, fonts.semiBold, 28, 36, "#111827", 1184));
  if (subtitle) header.appendChild(visualText(subtitle, fonts.medium, 14, 20, "#667085", 1184));
  panel.appendChild(header);
  return panel;
}

function visualFrame(name, mode, width) {
  const frame = figma.createFrame();
  frame.name = name;
  frame.layoutMode = mode;
  frame.fills = [];
  if (width) {
    frame.resize(width, 100);
    frame.primaryAxisSizingMode = mode === "HORIZONTAL" ? "FIXED" : "AUTO";
    frame.counterAxisSizingMode = mode === "HORIZONTAL" ? "AUTO" : "FIXED";
  } else {
    frame.counterAxisSizingMode = "AUTO";
    frame.primaryAxisSizingMode = "AUTO";
  }
  return frame;
}

function groupColorTokens(tokens) {
  const order = ["Brand", "Background", "Neutral", "Overlay", "Semantic", "Auxiliary", "Light", "Dark"];
  const groups = {};
  tokens.forEach((token) => {
    const group = colorGroupName(token.name);
    if (!groups[group]) groups[group] = [];
    groups[group].push(token);
  });
  return Object.fromEntries(
    Object.entries(groups).sort(([a], [b]) => {
      const ai = order.indexOf(a);
      const bi = order.indexOf(b);
      return (ai === -1 ? 99 : ai) - (bi === -1 ? 99 : bi) || a.localeCompare(b);
    }),
  );
}

function colorGroupName(name) {
  const parts = String(name || "").split("/");
  if (["Light", "Dark"].includes(parts[0]) && parts[1]) return parts[1];
  return parts[0] || "Color";
}

function shortTokenName(name) {
  const parts = String(name || "").split("/");
  if (["Light", "Dark"].includes(parts[0])) return `${parts[0]} / ${parts.slice(2).join("/")}`;
  return parts.slice(1).join("/") || name;
}

async function getLocalVariables() {
  if (figma.variables.getLocalVariablesAsync) return await figma.variables.getLocalVariablesAsync();
  return figma.variables.getLocalVariables();
}

async function getLocalCollections() {
  if (figma.variables.getLocalVariableCollectionsAsync) return await figma.variables.getLocalVariableCollectionsAsync();
  return figma.variables.getLocalVariableCollections();
}

async function getLocalPaintStyles() {
  if (figma.getLocalPaintStylesAsync) return await figma.getLocalPaintStylesAsync();
  return figma.getLocalPaintStyles();
}

async function getLocalTextStyles() {
  if (figma.getLocalTextStylesAsync) return await figma.getLocalTextStylesAsync();
  return figma.getLocalTextStyles();
}

async function getLocalEffectStyles() {
  if (figma.getLocalEffectStylesAsync) return await figma.getLocalEffectStylesAsync();
  return figma.getLocalEffectStyles();
}

async function setCurrentPage(page) {
  if (!page) return;
  if (figma.setCurrentPageAsync) {
    await figma.setCurrentPageAsync(page);
    return;
  }
  figma.currentPage = page;
}

async function getOrCreateCollection(name) {
  const collections = await getLocalCollections();
  const existing = collections.find((collection) => collection.name === name);
  if (existing) return existing;
  const collection = figma.variables.createVariableCollection(name);
  trackCreated("collections", collection);
  return collection;
}

async function createVariable(name, collection, type, options = {}) {
  const variables = await getLocalVariables();
  const existing = variables.find((item) => item.name === name && item.variableCollectionId === collection.id);
  if (existing) {
    markPluginOwned(existing);
    return existing;
  }
  try {
    const variable = figma.variables.createVariable(name, collection, type);
    trackCreated("variables", variable);
    markPluginOwned(variable);
    return variable;
  } catch (error) {
    if (options.optional) return null;
    throw error;
  }
}

async function preloadFonts(tokens) {
  const availableFonts = await getAvailableFonts();
  for (const token of tokens) {
    token.resolvedFontName = await loadFontWithFallback(token.family, token.weight, availableFonts);
    token.family = token.resolvedFontName.family;
    token.weight = token.resolvedFontName.style;
  }
}

async function loadFontWithFallback(family, style, availableFonts = []) {
  const candidates = fontStyleCandidates(style);
  const matchedFamily = matchFontFamily(family, availableFonts);
  const familyCandidates = [...new Set([matchedFamily, family].filter(Boolean))];
  for (const fontFamily of familyCandidates) {
    const availableStyles = availableFonts.filter((font) => font.fontName.family === fontFamily).map((font) => font.fontName.style);
    const matchedStyle = matchFontStyle(candidates, availableStyles);
    if (matchedStyle) {
      const fontName = { family: fontFamily, style: matchedStyle };
      await figma.loadFontAsync(fontName);
      return fontName;
    }
  }

  for (const candidate of candidates) {
    try {
      const fontName = { family, style: candidate };
      await figma.loadFontAsync(fontName);
      return fontName;
    } catch (error) {
      // Try the next common style spelling.
    }
  }
  throw new Error(`字体不可用：${family} / ${style}。请先在 Figma 中安装或启用这个字体。`);
}

async function getAvailableFonts() {
  try {
    return await figma.listAvailableFontsAsync();
  } catch (error) {
    return [];
  }
}

function matchFontFamily(family, availableFonts) {
  const target = normalizeFontKey(family);
  const match = availableFonts.find((font) => normalizeFontKey(font.fontName.family) === target);
  return match ? match.fontName.family : "";
}

function matchFontStyle(candidates, styles) {
  for (const candidate of candidates) {
    const direct = styles.find((style) => style === candidate);
    if (direct) return direct;
    const normalized = normalizeFontKey(candidate);
    const loose = styles.find((style) => normalizeFontKey(style) === normalized);
    if (loose) return loose;
  }
  return "";
}

function normalizeFontKey(value) {
  return String(value || "").replace(/[\s_-]+/g, "").toLowerCase();
}

function fontStyleCandidates(style) {
  const normalized = String(style || "Regular").trim();
  const compact = normalized.replace(/\s+/g, "");
  const candidates = [normalized, compact];
  if (/semi\s*bold/i.test(normalized)) candidates.push("SemiBold", "Semi Bold", "Semibold");
  if (/extra\s*bold/i.test(normalized)) candidates.push("ExtraBold", "Extra Bold");
  if (/regular/i.test(normalized)) candidates.push("Regular");
  if (/medium/i.test(normalized)) candidates.push("Medium");
  if (/bold/i.test(normalized)) candidates.push("Bold");
  return [...new Set(candidates)];
}

function fontWeightValue(weight) {
  const normalized = String(weight || "Regular").toLowerCase().replace(/\s+/g, "");
  if (normalized.includes("thin")) return 100;
  if (normalized.includes("extralight") || normalized.includes("ultralight")) return 200;
  if (normalized.includes("light")) return 300;
  if (normalized.includes("regular") || normalized.includes("normal")) return 400;
  if (normalized.includes("medium")) return 500;
  if (normalized.includes("semibold") || normalized.includes("demibold")) return 600;
  if (normalized.includes("extrabold") || normalized.includes("ultrabold")) return 800;
  if (normalized.includes("black") || normalized.includes("heavy")) return 900;
  if (normalized.includes("bold")) return 700;
  return 400;
}

function tokenToSolidPaint(token) {
  return {
    type: "SOLID",
    color: hexToFigmaRgb(token.value),
    opacity: token.opacity === undefined ? 1 : token.opacity,
  };
}

function gradientToPaint(token) {
  return {
    type: gradientPaintType(token.direction),
    gradientTransform: gradientTransform(token.direction),
    gradientStops: [
      { position: 0, color: { ...hexToFigmaRgb(token.from), a: 1 } },
      { position: 1, color: { ...hexToFigmaRgb(token.to), a: 1 } },
    ],
  };
}

function gradientPaintType(type) {
  if (type === "radial") return "GRADIENT_RADIAL";
  if (type === "angular") return "GRADIENT_ANGULAR";
  if (type === "diamond") return "GRADIENT_DIAMOND";
  return "GRADIENT_LINEAR";
}

function gradientTransform(type) {
  const direction = ["left-right", "top-bottom", "diagonal"].includes(type) ? type : "left-right";
  if (direction === "top-bottom") {
    return [
      [0, 1, 0],
      [-1, 0, 1],
    ];
  }
  if (direction === "diagonal") {
    return [
      [0.707, 0.707, -0.207],
      [-0.707, 0.707, 0.5],
    ];
  }
  return [
    [1, 0, 0],
    [0, 1, 0],
  ];
}

function paintToVariableValue(token) {
  const rgb = hexToFigmaRgb(token.value);
  return {
    r: rgb.r,
    g: rgb.g,
    b: rgb.b,
    a: token.opacity === undefined ? 1 : token.opacity,
  };
}

function rgbaToFigmaColor(value) {
  const match = String(value).match(/rgba\((\d+),\s*(\d+),\s*(\d+),\s*([0-9.]+)\)/);
  if (!match) {
    const rgb = hexToFigmaRgb(value);
    return { ...rgb, a: 1 };
  }
  return {
    r: Number(match[1]) / 255,
    g: Number(match[2]) / 255,
    b: Number(match[3]) / 255,
    a: Number(match[4]),
  };
}

function hexToFigmaRgb(hex) {
  const rgb = hexToRgb(hex);
  return { r: rgb.r / 255, g: rgb.g / 255, b: rgb.b / 255 };
}

function figmaColorToHex(color) {
  return rgbToHex({
    r: color.r * 255,
    g: color.g * 255,
    b: color.b * 255,
  });
}

function normalizeHex(value, fallback) {
  const raw = String(value || "").trim().replace(/^#/, "");
  if (/^[0-9a-fA-F]{3}$/.test(raw)) {
    return `#${raw.split("").map((char) => char + char).join("").toUpperCase()}`;
  }
  if (/^[0-9a-fA-F]{6}$/.test(raw)) return `#${raw.toUpperCase()}`;
  return fallback;
}

function hasValidHex(value) {
  const raw = String(value || "").trim().replace(/^#/, "");
  return /^[0-9a-fA-F]{3}$/.test(raw) || /^[0-9a-fA-F]{6}$/.test(raw);
}

function sanitizeTokenSegment(value) {
  const segment = String(value || "")
    .trim()
    .replace(/[\\/]+/g, "-")
    .replace(/\s+/g, "-")
    .replace(/^-+|-+$/g, "");
  return segment || "item";
}

function sanitizeModeName(value) {
  const name = String(value || "")
    .trim()
    .replace(/[\\/]+/g, "-")
    .replace(/\s+/g, " ");
  return name || "Theme";
}

function uniqueNames(names) {
  const seen = new Map();
  return names.map((name) => {
    const base = name || "Theme";
    const count = (seen.get(base) || 0) + 1;
    seen.set(base, count);
    return count === 1 ? base : `${base} ${count}`;
  });
}

function uniquifyThemeNames(themes) {
  const names = uniqueNames(themes.map((theme, index) => theme.name || `Theme ${index + 1}`));
  return themes.map((theme, index) => ({ ...theme, name: names[index] }));
}

function colorRef(name) {
  if (name === "white") return RULES.white;
  if (name === "darkAnchor") return RULES.darkAnchor;
  return name;
}

function hexToRgb(hex) {
  const clean = normalizeHex(hex, "#000000").slice(1);
  return {
    r: parseInt(clean.slice(0, 2), 16),
    g: parseInt(clean.slice(2, 4), 16),
    b: parseInt(clean.slice(4, 6), 16),
  };
}

function rgbToHex({ r, g, b }) {
  return `#${[r, g, b]
    .map((value) => Math.max(0, Math.min(255, Math.round(value))).toString(16).padStart(2, "0"))
    .join("")
    .toUpperCase()}`;
}

function rgbToHsl({ r, g, b }) {
  const red = r / 255;
  const green = g / 255;
  const blue = b / 255;
  const max = Math.max(red, green, blue);
  const min = Math.min(red, green, blue);
  const lightness = (max + min) / 2;
  const delta = max - min;
  if (delta === 0) return { h: 0, s: 0, l: lightness };

  const saturation = delta / (1 - Math.abs(2 * lightness - 1));
  let hue;
  if (max === red) hue = ((green - blue) / delta) % 6;
  else if (max === green) hue = (blue - red) / delta + 2;
  else hue = (red - green) / delta + 4;
  hue *= 60;
  if (hue < 0) hue += 360;
  return { h: hue, s: saturation, l: lightness };
}

function hslToHex({ h, s, l }) {
  const chroma = (1 - Math.abs(2 * l - 1)) * s;
  const x = chroma * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = l - chroma / 2;
  let r = 0;
  let g = 0;
  let b = 0;
  if (h < 60) [r, g, b] = [chroma, x, 0];
  else if (h < 120) [r, g, b] = [x, chroma, 0];
  else if (h < 180) [r, g, b] = [0, chroma, x];
  else if (h < 240) [r, g, b] = [0, x, chroma];
  else if (h < 300) [r, g, b] = [x, 0, chroma];
  else [r, g, b] = [chroma, 0, x];
  return rgbToHex({ r: (r + m) * 255, g: (g + m) * 255, b: (b + m) * 255 });
}

function hexToHsl(hex) {
  return rgbToHsl(hexToRgb(hex));
}

function hexToOklch(hex) {
  const rgb = hexToRgb(hex);
  const r = srgbToLinear(rgb.r / 255);
  const g = srgbToLinear(rgb.g / 255);
  const b = srgbToLinear(rgb.b / 255);
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
  const okL = 0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s;
  const okA = 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s;
  const okB = 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s;
  const chroma = Math.sqrt(okA * okA + okB * okB);
  const hue = ((Math.atan2(okB, okA) * 180) / Math.PI + 360) % 360;
  return { l: okL, c: chroma, h: hue };
}

function oklchToHex({ l, c, h }) {
  const hue = (h * Math.PI) / 180;
  const a = c * Math.cos(hue);
  const b = c * Math.sin(hue);
  const lPrime = l + 0.3963377774 * a + 0.2158037573 * b;
  const mPrime = l - 0.1055613458 * a - 0.0638541728 * b;
  const sPrime = l - 0.0894841775 * a - 1.291485548 * b;
  const lCube = lPrime * lPrime * lPrime;
  const mCube = mPrime * mPrime * mPrime;
  const sCube = sPrime * sPrime * sPrime;
  const r = linearToSrgb(4.0767416621 * lCube - 3.3077115913 * mCube + 0.2309699292 * sCube);
  const g = linearToSrgb(-1.2684380046 * lCube + 2.6097574011 * mCube - 0.3413193965 * sCube);
  const blue = linearToSrgb(-0.0041960863 * lCube - 0.7034186147 * mCube + 1.707614701 * sCube);
  return rgbToHex({ r: r * 255, g: g * 255, b: blue * 255 });
}

function srgbToLinear(value) {
  return value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4;
}

function linearToSrgb(value) {
  const clamped = clamp(value, 0, 1);
  return clamped <= 0.0031308 ? clamped * 12.92 : 1.055 * clamped ** (1 / 2.4) - 0.055;
}

function mix(hexA, hexB, amount) {
  const a = hexToRgb(hexA);
  const b = hexToRgb(hexB);
  return rgbToHex({
    r: a.r + (b.r - a.r) * amount,
    g: a.g + (b.g - a.g) * amount,
    b: a.b + (b.b - a.b) * amount,
  });
}

function rgbaString(hex, alpha) {
  const rgb = hexToRgb(hex);
  return `rgba(${rgb.r}, ${rgb.g}, ${rgb.b}, ${Number(alpha.toFixed(2))})`;
}

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
}

function summarizeResult(result) {
  return [
    `颜色变量：${result.colorVariables}`,
    `颜色样式：${result.colorStyles}`,
	    `渐变样式：${result.gradientStyles}`,
	    `数值变量：${result.numberVariables}`,
	    `字体变量：${result.typographyVariables}`,
	    `字体样式：${result.textStyles}`,
    `阴影样式：${result.effectStyles}`,
    `可视化节点：${result.visualNodes}`,
  ].join("\n");
}
